<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"laoren"
                    }
                ],
                "menu":"老人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"家人管理",
                        "menuJump":"列表",
                        "tableName":"jiaren"
                    }
                ],
                "menu":"家人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"机构社区人员管理",
                        "menuJump":"列表",
                        "tableName":"jigoushequ"
                    }
                ],
                "menu":"机构社区人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"服务记录管理",
                        "menuJump":"列表",
                        "tableName":"fuwujilu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"就诊记录管理",
                        "menuJump":"列表",
                        "tableName":"jiuzhenjilu"
                    }
					,
					 {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"求助服务管理",
                        "menuJump":"列表",
                        "tableName":"qiuzhu"
                    }
					,
					
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"随访记录管理",
                        "menuJump":"列表",
                        "tableName":"suifangjilu"
                    }

                ],
                "menu":"服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"娱乐活动管理",
                        "menuJump":"列表",
                        "tableName":"yule"
                    }
                ],
                "menu":"娱乐活动管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
			,{
                "child":[
                    
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"评价星级类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFuwujilu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"就诊类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQiuzhu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"养老方式类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYanglaofanghsi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"活动类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYule"
                    }

                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"laoren"
                    }
                ],
                "menu":"老人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家人管理",
                        "menuJump":"列表",
                        "tableName":"jiaren"
                    }
                ],
                "menu":"家人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"服务记录管理",
                        "menuJump":"列表",
                        "tableName":"fuwujilu"
                    }
                ],
                "menu":"服务记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"就诊记录管理",
                        "menuJump":"列表",
                        "tableName":"jiuzhenjilu"
                    }
                ],
                "menu":"就诊记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"求助服务管理",
                        "menuJump":"列表",
                        "tableName":"qiuzhu"
                    }
                ],
                "menu":"求助服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"随访记录管理",
                        "menuJump":"列表",
                        "tableName":"suifangjilu"
                    }
                ],
                "menu":"随访记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改"
                        ],
                        "menu":"娱乐活动管理",
                        "menuJump":"列表",
                        "tableName":"yule"
                    }
                ],
                "menu":"娱乐活动管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"机构社区人员",
        "tableName":"jigoushequ"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家人管理",
                        "menuJump":"列表",
                        "tableName":"jiaren"
                    }
                ],
                "menu":"家人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"服务记录管理",
                        "menuJump":"列表",
                        "tableName":"fuwujilu"
                    }
                ],
                "menu":"服务记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"就诊记录管理",
                        "menuJump":"列表",
                        "tableName":"jiuzhenjilu"
                    }
                ],
                "menu":"就诊记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"求助服务管理",
                        "menuJump":"列表",
                        "tableName":"qiuzhu"
                    }
                ],
                "menu":"求助服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"随访记录管理",
                        "menuJump":"列表",
                        "tableName":"suifangjilu"
                    }
                ],
                "menu":"随访记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"娱乐活动管理",
                        "menuJump":"列表",
                        "tableName":"yule"
                    }
                ],
                "menu":"娱乐活动管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"老人",
        "tableName":"laoren"
    }
	,
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"laoren"
                    }
                ],
                "menu":"老人管理"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家人管理",
                        "menuJump":"列表",
                        "tableName":"jiaren"
                    }
                ],
                "menu":"家人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"服务记录管理",
                        "menuJump":"列表",
                        "tableName":"fuwujilu"
                    }
                ],
                "menu":"服务记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"就诊记录管理",
                        "menuJump":"列表",
                        "tableName":"jiuzhenjilu"
                    }
                ],
                "menu":"就诊记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"求助服务管理",
                        "menuJump":"列表",
                        "tableName":"qiuzhu"
                    }
                ],
                "menu":"求助服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"随访记录管理",
                        "menuJump":"列表",
                        "tableName":"suifangjilu"
                    }
                ],
                "menu":"随访记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"娱乐活动管理",
                        "menuJump":"列表",
                        "tableName":"yule"
                    }
                ],
                "menu":"娱乐活动管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"家人",
        "tableName":"jiaren"
    }
];

var hasMessage = '';
